name: Publish Packages to npmjs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating github releases
      id-token: write
    environment: publish
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Extract version from tag
        id: extract_version
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          version="${tag#v}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Update package versions
        run: |
          # Update version in all package.json files
          npm version ${{ steps.extract_version.outputs.version }} --workspaces --no-git-tag-version
          # Convert file dependencies to published versions for publishing
          sed -i 's/"file:\.\.\/common"/"^${{ steps.extract_version.outputs.version }}"/g' packages/*/package.json

      - name: Publish packages
        run: |
          npm publish --workspace=@json-feed-types/common --provenance --access public
          npm publish --workspace=@json-feed-types/1_1 --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.extract_version.outputs.tag }}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            --generate-notes
